[metadata]
name = "{{PACK_NAME}}"
description = "Atlas starter template"

[versions]
mc = "1.21.11"
modloader = "neoforge"
modloader_version = "21.11.38-beta"

[cli]
hub_url = "https://atlas.nathanm.org"
pack_id = "i15LAF-2l10Ss7itSBfJC"
default_channel = "dev"



