[metadata]
name = "{{PACK_NAME}}"
description = "Atlas starter template"

[versions]
mc = "1.21.11"
modloader = "fabric"
modloader_version = "0.18.4"

[cli]
hub_url = "https://atlas.nathanm.org"
pack_id = "i15LAF-2l10Ss7itSBfJC"
default_channel = "dev"



