[metadata]
name = "fabric-api-0.141.3+1.21.11.jar"
side = "both"
project_url = "https://modrinth.com/project/P7dR8mSH"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "P7dR8mSH"
version = "i5tSkVBH"
url = "https://cdn.modrinth.com/data/P7dR8mSH/versions/i5tSkVBH/fabric-api-0.141.3%2B1.21.11.jar"

[download.hashes]
sha1 = "50de67eb221f0b38216da8668b09ca311327040e"
sha512 = "c20c017e23d6d2774690d0dd774cec84c16bfac5461da2d9345a1cd95eee495b1954333c421e3d1c66186284d24a433f6b0cced8021f62e0bfa617d2384d0471"
