[metadata]
name = "iris-fabric-1.10.5+mc1.21.11.jar"
side = "both"
project_url = "https://modrinth.com/project/YL57xq9U"
disabled_client_oses = []

[download]
source = "modrinth"
project_id = "YL57xq9U"
version = "ZQx4ktUs"
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/ZQx4ktUs/iris-fabric-1.10.5%2Bmc1.21.11.jar"

[download.hashes]
sha1 = "8f56581bb74c845b702d07488cd9b8adffaae497"
sha512 = "e42a65e03c324c44847255e255dba4e75d65093bccd2b4e4804f297bf8505e218fbd5a600b8dda8fbe73229eb90ae710c7133e43aa2029b961a686600539ed79"
